' ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
'< _gui.bas modul generated by utility                       GladeToBac V3.0.3 >
'< Modul _gui.bas erzeugt von                                                  >
'< Generated at / Generierung am                             2011-11-21, 16:24 >
' -----------------------------------------------------------------------------
'< Main/Haupt Program name: GladeToBac.bas                                     >
'<  Email:  Thomas[ dot ]Freiherr{ at }gmx{ dot }net                           >
'<    WWW:  www.freebasic-portal.de                                            >
' -----------------------------------------------------------------------------
'< load GUI-XML-data into memory                                  do not edit! >
'< liest GUI-XML-Daten in den Speicher                       nicht veraendern! >
' vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

GUI.GUIstr =_
"<?xml version=""1.0"" encoding=""UTF-8""?>" & _
"<interface>" & _
"<requires lib=""gtk+"" version=""2.16""/>" & _
"<object class=""GtkActionGroup"" id=""ActMain"">" & _
"<child>" & _
"<object class=""GtkAction"" id=""action1"">" & _
"<property name=""label"" translatable=""yes"">_Quit</property>" & _
"<property name=""short_label"" translatable=""yes"">_Quit</property>" & _
"<property name=""tooltip"" translatable=""yes"">end application</property>" & _
"<property name=""stock_id"">gtk-quit</property>" & _
"<signal name=""activate"" handler=""gtk_main_quit"" swapped=""no""/>" & _
"</object>" & _
"<accelerator key=""q"" modifiers=""GDK_CONTROL_MASK""/>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkAction"" id=""action2"">" & _
"<property name=""label"" translatable=""yes"">Generate _FB files</property>" & _
"<property name=""short_label"" translatable=""yes"">Generate _FB files</property>" & _
"<property name=""tooltip"" translatable=""yes"">write files:" & CHR(10) & _
"-&gt; *_tobac.bas (allways)" & CHR(10) & _
"-&gt; *.bas and callbacks *.bas (if not exists)" & CHR(10) & _
"-&gt; GUI-source *_gui.bas (if required)" & CHR(10) & _
"[active after GUI-XML-file loaded]</property>" & _
"<property name=""stock_id"">gtk-edit</property>" & _
"<signal name=""activate"" handler=""on_ActGenerate_activate"" swapped=""no""/>" & _
"</object>" & _
"<accelerator key=""f"" modifiers=""GDK_CONTROL_MASK""/>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkAction"" id=""action3"">" & _
"<property name=""label"" translatable=""yes"">generate _pot file (I18N)</property>" & _
"<property name=""short_label"" translatable=""yes"">I18N</property>" & _
"<property name=""tooltip"" translatable=""yes"">scan translatable texts in source files and generate a *.pot file for poedit (*.bas in main folder and tobac folder, *.ui/*.glade in main folder)" & CHR(10) & _
"[active after GUI-XML-file loaded]</property>" & _
"<property name=""stock_id"">gtk-index</property>" & _
"<signal name=""activate"" handler=""on_ActI18N_activate"" swapped=""no""/>" & _
"</object>" & _
"<accelerator key=""i"" modifiers=""GDK_CONTROL_MASK""/>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkAction"" id=""action4"">" & _
"<property name=""label"" translatable=""yes"">_Load / analyse</property>" & _
"<property name=""short_label"" translatable=""yes"">_Load</property>" & _
"<property name=""tooltip"" translatable=""yes"">choose GUI-XML-file (*.ui/*.glade), load and check it for further processing (read-only operations)</property>" & _
"<property name=""stock_id"">gtk-open</property>" & _
"<signal name=""activate"" handler=""on_ActLoad_activate"" swapped=""no""/>" & _
"</object>" & _
"<accelerator key=""o"" modifiers=""GDK_CONTROL_MASK""/>" & _
"</child>" & _
"</object>" & _
"<object class=""GtkListStore"" id=""ComboLiSto"">" & _
"<columns>" & _
"<!-- column-name Lizenzen -->" & _
"<column type=""gchararray""/>" & _
"</columns>" & _
"</object>" & _
"<object class=""GtkAboutDialog"" id=""WinAbout"">" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""border_width"">5</property>" & _
"<property name=""modal"">True</property>" & _
"<property name=""window_position"">center-on-parent</property>" & _
"<property name=""destroy_with_parent"">True</property>" & _
"<property name=""icon_name"">gtk-about</property>" & _
"<property name=""type_hint"">normal</property>" & _
"<property name=""transient_for"">WinMain</property>" & _
"<property name=""copyright"" translatable=""yes"">GPLv3</property>" & _
"<property name=""comments"" translatable=""yes"">FreeBasic code sketcher</property>" & _
"<property name=""website"">http://www.freebasic-portal.de/downloads/ressourcencompiler/</property>" & _
"<property name=""website_label"" translatable=""yes"">FreeBASIC-Portal</property>" & _
"<property name=""license"" translatable=""yes"">This program is free software: you can redistribute it and/or modify it under" & CHR(10) & _
"the terms of the GNU General Public License as published by the Free Software" & CHR(10) & _
"Foundation, either version 3 of the License, or (at your option) any later" & CHR(10) & _
"version." & CHR(10) & _
"" & CHR(10) & _
"This program is distributed in the hope that it will be useful, but WITHOUT" & CHR(10) & _
"ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS" & CHR(10) & _
"FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more" & CHR(10) & _
"details." & CHR(10) & _
"" & CHR(10) & _
"You should have received a copy of the GNU General Public License along with" & CHR(10) & _
"this program.  If not, see &lt;http://www.gnu.org/licenses/&gt;." & CHR(10) & _
"</property>" & _
"<property name=""authors"">information@siebke.com" & CHR(10) & _
"Thomas.Freiherr@gmx.net" & CHR(10) & _
"galeon@ymail.com</property>" & _
"<property name=""documenters"">Thomas.Freiherr@gmx.net</property>" & _
"<property name=""translator_credits"" translatable=""yes"">Thomas.Freiherr@gmx.net</property>" & _
"<property name=""artists"">Thomas.Freiherr@gmx.net</property>" & _
"<child internal-child=""vbox"">" & _
"<object class=""GtkBox"" id=""dialog-vbox1"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""spacing"">2</property>" & _
"<child internal-child=""action_area"">" & _
"<object class=""GtkButtonBox"" id=""dialog-action_area1"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""layout_style"">end</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">False</property>" & _
"<property name=""fill"">True</property>" & _
"<property name=""pack_type"">end</property>" & _
"<property name=""position"">0</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<placeholder/>" & _
"</child>" & _
"</object>" & _
"</child>" & _
"</object>" & _
"<object class=""GtkWindow"" id=""WinMain"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""border_width"">5</property>" & _
"<property name=""window_position"">center</property>" & _
"<accel-groups>" & _
"<group name=""accelgroup1""/>" & _
"</accel-groups>" & _
"<signal name=""configure-event"" handler=""on_win_main_configure_event"" swapped=""no""/>" & _
"<signal name=""delete-event"" handler=""gtk_main_quit"" swapped=""no""/>" & _
"<child>" & _
"<object class=""GtkVBox"" id=""vbox2"">" & _
"<property name=""width_request"">560</property>" & _
"<property name=""height_request"">460</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""spacing"">5</property>" & _
"<child>" & _
"<object class=""GtkMenuBar"" id=""GtkMenuBar1"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<child>" & _
"<object class=""GtkMenuItem"" id=""GtkMenuItem1"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""label"" translatable=""yes"">_File   </property>" & _
"<property name=""use_underline"">True</property>" & _
"<child type=""submenu"">" & _
"<object class=""GtkMenu"" id=""GtkMenu1"">" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""border_width"">5</property>" & _
"<property name=""accel_group"">accelgroup1</property>" & _
"<child>" & _
"<object class=""GtkImageMenuItem"" id=""GtkImageMenuItem1"">" & _
"<property name=""label"" translatable=""yes"">_Load / analyse</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">choose GUI-XML-file (*.ui/*.glade), load and check it for further processing (read-only operations)</property>" & _
"<property name=""related_action"">action4</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""accel_path"">&lt;GTK-tobac&gt;/File/Load</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""image"">image2</property>" & _
"<property name=""use_stock"">False</property>" & _
"<property name=""accel_group"">accelgroup1</property>" & _
"<accelerator key=""o"" signal=""activate"" modifiers=""GDK_CONTROL_MASK""/>" & _
"</object>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkSeparatorMenuItem"" id=""separatormenuitem1"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"</object>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkImageMenuItem"" id=""MnuSave"">" & _
"<property name=""label"" translatable=""yes"">Save _project parameters</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""sensitive"">False</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">Save parameters:" & CHR(10) & _
"CURPATH/GTK+tobac.ini." & CHR(10) & _
"[active after GUI-XML-file loaded]</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""accel_path"">&lt;GTK-tobac&gt;/File/Save</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""image"">image1</property>" & _
"<property name=""use_stock"">False</property>" & _
"<property name=""accel_group"">accelgroup1</property>" & _
"<accelerator key=""s"" signal=""activate"" modifiers=""GDK_CONTROL_MASK""/>" & _
"<signal name=""activate"" handler=""on_MnuSaPa_activate"" swapped=""no""/>" & _
"</object>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkImageMenuItem"" id=""GtkImageMenuItem2"">" & _
"<property name=""label"" translatable=""yes"">Save _default parameters</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">Save parameters:" & CHR(10) & _
"EXEPATH/GTK+tobac.ini.</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""accel_path"">&lt;GTK-tobac&gt;/File/SaveAs</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""image"">image6</property>" & _
"<property name=""use_stock"">False</property>" & _
"<property name=""accel_group"">accelgroup1</property>" & _
"<accelerator key=""s"" signal=""activate"" modifiers=""GDK_SHIFT_MASK | GDK_CONTROL_MASK""/>" & _
"<signal name=""activate"" handler=""on_MnuSaPa_activate"" swapped=""no""/>" & _
"</object>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkSeparatorMenuItem"" id=""separatormenuitem2"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"</object>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkImageMenuItem"" id=""MnuMist"">" & _
"<property name=""label"" translatable=""yes"">_Clean-up</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""sensitive"">False</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">check for deprecated callbacks *.bas and offer to delete them." & CHR(10) & _
"[active after GUI-XML-file loaded]</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""accel_path"">&lt;GTK-tobac&gt;/File/Mist</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""image"">image3</property>" & _
"<property name=""use_stock"">False</property>" & _
"<property name=""accel_group"">accelgroup1</property>" & _
"<accelerator key=""a"" signal=""activate"" modifiers=""GDK_CONTROL_MASK""/>" & _
"<signal name=""activate"" handler=""on_MnuMist_activate"" swapped=""no""/>" & _
"</object>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkSeparatorMenuItem"" id=""separatormenuitem3"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"</object>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkImageMenuItem"" id=""GtkImageMenuItem5"">" & _
"<property name=""label"" translatable=""yes"">_Quit</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">end application</property>" & _
"<property name=""related_action"">action1</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""accel_path"">&lt;GTK-tobac&gt;/File/Quit</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""image"">image5</property>" & _
"<property name=""use_stock"">False</property>" & _
"<property name=""accel_group"">accelgroup1</property>" & _
"<accelerator key=""q"" signal=""activate"" modifiers=""GDK_CONTROL_MASK""/>" & _
"</object>" & _
"</child>" & _
"</object>" & _
"</child>" & _
"</object>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkMenuItem"" id=""GtkMenuItem2"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""label"" translatable=""yes"">_Execute   </property>" & _
"<property name=""use_underline"">True</property>" & _
"<child type=""submenu"">" & _
"<object class=""GtkMenu"" id=""GtkMenu2"">" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""border_width"">5</property>" & _
"<property name=""accel_group"">accelgroup1</property>" & _
"<child>" & _
"<object class=""GtkImageMenuItem"" id=""MnuBas"">" & _
"<property name=""label"" translatable=""yes"">Generate _FB files</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">write files:" & CHR(10) & _
"-&gt; *_tobac.bas (allways)" & CHR(10) & _
"-&gt; *.bas and callbacks *.bas (if not exists)" & CHR(10) & _
"-&gt; GUI-source *_gui.bas (if required)" & CHR(10) & _
"[active after GUI-XML-file loaded]</property>" & _
"<property name=""related_action"">action2</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""accel_path"">&lt;GTK-tobac&gt;/Exec/Bas</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""image"">image4</property>" & _
"<property name=""use_stock"">False</property>" & _
"<property name=""accel_group"">accelgroup1</property>" & _
"</object>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkSeparatorMenuItem"" id=""separatormenuitem4"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"</object>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkImageMenuItem"" id=""MnuI18N"">" & _
"<property name=""label"" translatable=""yes"">Generate _pot file (_I18N)</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">scan translatable texts in source files and generate a *.pot file for poedit (*.bas in main folder and tobac folder, *.ui/*.glade in main folder)" & CHR(10) & _
"[active after GUI-XML-file loaded]</property>" & _
"<property name=""related_action"">action3</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""accel_path"">&lt;GTK-tobac&gt;/Exec/I18N</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""image"">image7</property>" & _
"<property name=""use_stock"">False</property>" & _
"<property name=""accel_group"">accelgroup1</property>" & _
"</object>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkSeparatorMenuItem"" id=""separatormenuitem5"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"</object>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkImageMenuItem"" id=""MnuPro"">" & _
"<property name=""label"" translatable=""yes"">Generate _project files</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""sensitive"">False</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">write required project files (existing files don't get touched)" & CHR(10) & _
"[active after GUI-XML-file loaded]</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""accel_path"">&lt;GTK-tobac&gt;/Exec/Pro</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""image"">image8</property>" & _
"<property name=""use_stock"">False</property>" & _
"<property name=""accel_group"">accelgroup1</property>" & _
"<accelerator key=""p"" signal=""activate"" modifiers=""GDK_CONTROL_MASK""/>" & _
"<signal name=""activate"" handler=""on_MnuPro_activate"" swapped=""no""/>" & _
"</object>" & _
"</child>" & _
"</object>" & _
"</child>" & _
"</object>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkMenuItem"" id=""GtkMenuItem3"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""label"" translatable=""yes"">_Help   </property>" & _
"<property name=""use_underline"">True</property>" & _
"<child type=""submenu"">" & _
"<object class=""GtkMenu"" id=""GtkMenu3"">" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""border_width"">5</property>" & _
"<property name=""accel_group"">accelgroup1</property>" & _
"<child>" & _
"<object class=""GtkImageMenuItem"" id=""GtkImageMenuItem8"">" & _
"<property name=""label"">gtk-help</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">show file ReadMe.txt and command line help in output tab</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""accel_path"">&lt;GTK-tobac&gt;/Help/Help</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""use_stock"">True</property>" & _
"<property name=""accel_group"">accelgroup1</property>" & _
"<accelerator key=""h"" signal=""activate"" modifiers=""GDK_CONTROL_MASK""/>" & _
"<signal name=""activate"" handler=""on_MnuHelp_activate"" swapped=""no""/>" & _
"</object>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkSeparatorMenuItem"" id=""separatormenuitem6"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"</object>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkImageMenuItem"" id=""GtkImageMenuItem9"">" & _
"<property name=""label"">gtk-about</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">show info about this application</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""accel_path"">&lt;GTK-tobac&gt;/Help/About</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""use_stock"">True</property>" & _
"<property name=""accel_group"">accelgroup1</property>" & _
"<accelerator key=""i"" signal=""activate"" modifiers=""GDK_CONTROL_MASK""/>" & _
"<signal name=""activate"" handler=""on_MnuInfo_activate"" swapped=""no""/>" & _
"</object>" & _
"</child>" & _
"</object>" & _
"</child>" & _
"</object>" & _
"</child>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">False</property>" & _
"<property name=""fill"">False</property>" & _
"<property name=""position"">0</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkToolbar"" id=""toolbar1"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""toolbar_style"">both</property>" & _
"<child>" & _
"<object class=""GtkToolButton"" id=""GtkToolButton1"">" & _
"<property name=""width_request"">120</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""has_tooltip"">True</property>" & _
"<property name=""related_action"">action4</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">True</property>" & _
"<property name=""homogeneous"">True</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkSeparatorToolItem"" id=""separatortoolitem19"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">False</property>" & _
"<property name=""homogeneous"">True</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkToolButton"" id=""TobBas"">" & _
"<property name=""width_request"">120</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""has_tooltip"">True</property>" & _
"<property name=""related_action"">action2</property>" & _
"<property name=""label"" translatable=""yes"">Generate .bas</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">True</property>" & _
"<property name=""homogeneous"">True</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkSeparatorToolItem"" id=""separatortoolitem18"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">False</property>" & _
"<property name=""homogeneous"">True</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkToolButton"" id=""TobI18N"">" & _
"<property name=""width_request"">120</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""has_tooltip"">True</property>" & _
"<property name=""related_action"">action3</property>" & _
"<property name=""label"" translatable=""yes"">I18N</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">True</property>" & _
"<property name=""homogeneous"">True</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkSeparatorToolItem"" id=""separatortoolitem20"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">False</property>" & _
"<property name=""homogeneous"">True</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkToolButton"" id=""GtkToolButton4"">" & _
"<property name=""width_request"">130</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""has_tooltip"">True</property>" & _
"<property name=""related_action"">action1</property>" & _
"<property name=""label"" translatable=""yes"">Quit</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">True</property>" & _
"<property name=""homogeneous"">True</property>" & _
"</packing>" & _
"</child>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">False</property>" & _
"<property name=""fill"">False</property>" & _
"<property name=""position"">1</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkNotebook"" id=""NotMain"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">True</property>" & _
"<property name=""has_focus"">True</property>" & _
"<child>" & _
"<object class=""GtkHBox"" id=""hbox1"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""border_width"">5</property>" & _
"<property name=""spacing"">5</property>" & _
"<child>" & _
"<object class=""GtkVBox"" id=""vbox3"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<child>" & _
"<object class=""GtkFrame"" id=""frame5"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""label_xalign"">0</property>" & _
"<property name=""shadow_type"">in</property>" & _
"<child>" & _
"<object class=""GtkTable"" id=""table2"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""border_width"">5</property>" & _
"<property name=""n_rows"">7</property>" & _
"<property name=""n_columns"">3</property>" & _
"<property name=""column_spacing"">5</property>" & _
"<property name=""row_spacing"">5</property>" & _
"<child>" & _
"<object class=""GtkLabel"" id=""GtkLabel1"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""xalign"">1</property>" & _
"<property name=""label"" translatable=""yes"">_Synopsis:</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""mnemonic_widget"">EntSyn</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""top_attach"">3</property>" & _
"<property name=""bottom_attach"">4</property>" & _
"<property name=""x_options"">GTK_FILL</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkEntry"" id=""EntSyn"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">True</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">Short description of Project." & CHR(10) & _
"(used in *.bas, make, ReadMe.txt, *.geany, *.fbp)" & CHR(10) & _
"A long version will be imported from the file *.desc, if exists." & CHR(10) & _
"(used in *.bas, ReadMe.txt)</property>" & _
"<property name=""invisible_char"">●</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""left_attach"">1</property>" & _
"<property name=""right_attach"">3</property>" & _
"<property name=""top_attach"">3</property>" & _
"<property name=""bottom_attach"">4</property>" & _
"<property name=""x_options"">GTK_EXPAND | GTK_SHRINK | GTK_FILL</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkComboBox"" id=""ComLiz"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">Choose license" & CHR(10) & _
"(used in *.bas, make, ReadMe.txt)</property>" & _
"<property name=""model"">ComboLiSto</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""right_attach"">3</property>" & _
"<property name=""top_attach"">6</property>" & _
"<property name=""bottom_attach"">7</property>" & _
"<property name=""x_options"">GTK_EXPAND | GTK_SHRINK | GTK_FILL</property>" & _
"<property name=""y_options"">GTK_EXPAND</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkLabel"" id=""GtkLabel2"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""xalign"">1</property>" & _
"<property name=""label"" translatable=""yes"">_Version:</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""mnemonic_widget"">EntVer</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""top_attach"">4</property>" & _
"<property name=""bottom_attach"">5</property>" & _
"<property name=""x_options"">GTK_FILL</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkEntry"" id=""EntVer"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">True</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">Start version of project. Later, the version will be red from *.bas, if exists.</property>" & _
"<property name=""invisible_char"">●</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""left_attach"">1</property>" & _
"<property name=""right_attach"">2</property>" & _
"<property name=""top_attach"">4</property>" & _
"<property name=""bottom_attach"">5</property>" & _
"<property name=""x_options"">GTK_EXPAND | GTK_SHRINK | GTK_FILL</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkEntry"" id=""EntWeb"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">True</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">Insert webside URL, e.g. 'http://www.meins.net'" & CHR(10) & _
"(used in *.bas, make, ReadMe.txt)</property>" & _
"<property name=""invisible_char"">●</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""left_attach"">1</property>" & _
"<property name=""right_attach"">3</property>" & _
"<property name=""top_attach"">2</property>" & _
"<property name=""bottom_attach"">3</property>" & _
"<property name=""x_options"">GTK_EXPAND | GTK_SHRINK | GTK_FILL</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkEntry"" id=""EntEmail"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">True</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">Insert Email adress, e.g. 'My.Name@home.net' (! mind spamers !)" & CHR(10) & _
"(used in *.bas, *.po, make, ReadMe.txt)</property>" & _
"<property name=""invisible_char"">●</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""left_attach"">1</property>" & _
"<property name=""right_attach"">3</property>" & _
"<property name=""top_attach"">1</property>" & _
"<property name=""bottom_attach"">2</property>" & _
"<property name=""x_options"">GTK_EXPAND | GTK_SHRINK | GTK_FILL</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkEntry"" id=""EntName"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">True</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">Insert Name" & CHR(10) & _
"(used in *.bas, *.po, make, ReadMe.txt, *.rc)</property>" & _
"<property name=""invisible_char"">●</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""left_attach"">1</property>" & _
"<property name=""right_attach"">3</property>" & _
"<property name=""x_options"">GTK_EXPAND | GTK_SHRINK | GTK_FILL</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkLabel"" id=""GtkLabel3"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""xalign"">1</property>" & _
"<property name=""label"" translatable=""yes"">_Author:</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""mnemonic_widget"">EntName</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""x_options"">GTK_FILL</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkLabel"" id=""GtkLabel4"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""xalign"">1</property>" & _
"<property name=""label"" translatable=""yes"">_Email:</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""mnemonic_widget"">EntEmail</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""top_attach"">1</property>" & _
"<property name=""bottom_attach"">2</property>" & _
"<property name=""x_options"">GTK_FILL</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkLabel"" id=""GtkLabel5"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""xalign"">1</property>" & _
"<property name=""label"" translatable=""yes"">_Website:</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""mnemonic_widget"">EntWeb</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""top_attach"">2</property>" & _
"<property name=""bottom_attach"">3</property>" & _
"<property name=""x_options"">GTK_FILL</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkEntry"" id=""EntTyNa"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">True</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">Name of TYPE-definition, used for UI-variables (references to widgets/Objects)." & CHR(10) & _
"When empty:" & CHR(10) & _
"all UI-variables are global.</property>" & _
"<property name=""invisible_char"">●</property>" & _
"<property name=""width_chars"">8</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""left_attach"">1</property>" & _
"<property name=""right_attach"">2</property>" & _
"<property name=""top_attach"">5</property>" & _
"<property name=""bottom_attach"">6</property>" & _
"<property name=""x_options"">GTK_EXPAND | GTK_SHRINK | GTK_FILL</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkLabel"" id=""GtkLabel6"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""xalign"">1</property>" & _
"<property name=""label"" translatable=""yes"">T_YPE name:</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""mnemonic_widget"">EntTyNa</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""top_attach"">5</property>" & _
"<property name=""bottom_attach"">6</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkCheckButton"" id=""CheI18N"">" & _
"<property name=""label"" translatable=""yes"">I18_N support</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""receives_default"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">When aktiv:" & CHR(10) & _
"generate code to include and initialise libintl for internationalisation</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""xalign"">1</property>" & _
"<property name=""image_position"">right</property>" & _
"<property name=""draw_indicator"">True</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""left_attach"">2</property>" & _
"<property name=""right_attach"">3</property>" & _
"<property name=""top_attach"">5</property>" & _
"<property name=""bottom_attach"">6</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkCheckButton"" id=""CheTobac"">" & _
"<property name=""label"" translatable=""yes"">_tobac folder</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""receives_default"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">When active:" & CHR(10) & _
"generate *_tobac.bas [*_gui.bas] and callbacks *.bas in subfolder tobac.</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""xalign"">1</property>" & _
"<property name=""image_position"">right</property>" & _
"<property name=""draw_indicator"">True</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""left_attach"">2</property>" & _
"<property name=""right_attach"">3</property>" & _
"<property name=""top_attach"">4</property>" & _
"<property name=""bottom_attach"">5</property>" & _
"</packing>" & _
"</child>" & _
"</object>" & _
"</child>" & _
"<child type=""label"">" & _
"<object class=""GtkLabel"" id=""LabNeuPro"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""xpad"">5</property>" & _
"<property name=""label"" translatable=""yes"">&lt;b&gt;New project&lt;/b&gt;</property>" & _
"<property name=""use_markup"">True</property>" & _
"</object>" & _
"</child>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">True</property>" & _
"<property name=""fill"">True</property>" & _
"<property name=""position"">0</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkFrame"" id=""frame1"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""label_xalign"">0</property>" & _
"<property name=""shadow_type"">in</property>" & _
"<child>" & _
"<object class=""GtkTable"" id=""table1"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""border_width"">5</property>" & _
"<property name=""n_columns"">3</property>" & _
"<property name=""column_spacing"">5</property>" & _
"<property name=""row_spacing"">5</property>" & _
"<child>" & _
"<object class=""GtkCheckButton"" id=""CheGlaIn"">" & _
"<property name=""label"" translatable=""yes"">GUI _in source</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""receives_default"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">When active:" & CHR(10) & _
"generate *_gui.bas and include the file into the source code. In this case the GUI-XML-file needs NOT to be shiped with the binary.</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""xalign"">1</property>" & _
"<property name=""image_position"">right</property>" & _
"<property name=""draw_indicator"">True</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""left_attach"">2</property>" & _
"<property name=""right_attach"">3</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkLabel"" id=""GtkLabel7"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""xalign"">1</property>" & _
"<property name=""label"">GTK-Ver_s &gt;=</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""mnemonic_widget"">EntGtkVer</property>" & _
"</object>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkEntry"" id=""EntGtkVer"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">True</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">This GTK+ version gets checked at startup (ie '2.16')." & CHR(10) & _
"Minimum is 2.8." & CHR(10) & _
"When empty:" & CHR(10) & _
"no version check gets performed.</property>" & _
"<property name=""invisible_char"">●</property>" & _
"<property name=""width_chars"">8</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""left_attach"">1</property>" & _
"<property name=""right_attach"">2</property>" & _
"<property name=""x_options"">GTK_EXPAND | GTK_SHRINK | GTK_FILL</property>" & _
"</packing>" & _
"</child>" & _
"</object>" & _
"</child>" & _
"<child type=""label"">" & _
"<object class=""GtkLabel"" id=""LabTob"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""xpad"">5</property>" & _
"<property name=""label"" translatable=""yes"">&lt;b&gt;New project_tobac.bas&lt;/b&gt;</property>" & _
"<property name=""use_markup"">True</property>" & _
"</object>" & _
"</child>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">False</property>" & _
"<property name=""fill"">False</property>" & _
"<property name=""position"">1</property>" & _
"</packing>" & _
"</child>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">True</property>" & _
"<property name=""fill"">True</property>" & _
"<property name=""position"">0</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkFrame"" id=""frame2"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""label_xalign"">0</property>" & _
"<property name=""shadow_type"">in</property>" & _
"<child>" & _
"<object class=""GtkVBox"" id=""vbox4"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""border_width"">5</property>" & _
"<property name=""homogeneous"">True</property>" & _
"<child>" & _
"<object class=""GtkCheckButton"" id=""CheReadMe"">" & _
"<property name=""label"">_readme.txt</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""receives_default"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">When active:" & CHR(10) & _
"generate 'readme.txt' in main folder, if not exists</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""xalign"">0</property>" & _
"<property name=""draw_indicator"">True</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">True</property>" & _
"<property name=""fill"">True</property>" & _
"<property name=""position"">0</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkCheckButton"" id=""CheMake"">" & _
"<property name=""label"">_makefile</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""receives_default"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">When active:" & CHR(10) & _
"generate 'makefile' in main folder, if not exists</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""xalign"">0</property>" & _
"<property name=""draw_indicator"">True</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">True</property>" & _
"<property name=""fill"">True</property>" & _
"<property name=""position"">1</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkCheckButton"" id=""CheGeany"">" & _
"<property name=""label"">_Geany (*.geany)</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""receives_default"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">When active:" & CHR(10) & _
"generate Geany project file '*.geany' in main folder, if not exists</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""xalign"">0</property>" & _
"<property name=""draw_indicator"">True</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">True</property>" & _
"<property name=""fill"">True</property>" & _
"<property name=""position"">2</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkCheckButton"" id=""CheFbIde"">" & _
"<property name=""label"">FB-_IDE (*.fbide.fbp)</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""receives_default"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">When active:" & CHR(10) & _
"generate FB-IDE project file '*.fbide.fbp' in main folder, if not exists</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""xalign"">0</property>" & _
"<property name=""draw_indicator"">True</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">True</property>" & _
"<property name=""fill"">True</property>" & _
"<property name=""position"">3</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkCheckButton"" id=""CheFbEdit"">" & _
"<property name=""label"">FB-Edit (*_.fbp)</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""receives_default"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">When active:" & CHR(10) & _
"generate FB-Edit-Projekt-file '*.fbp' in main folder, if not exists</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""xalign"">0</property>" & _
"<property name=""draw_indicator"">True</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">True</property>" & _
"<property name=""fill"">True</property>" & _
"<property name=""position"">4</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkCheckButton"" id=""CheJelly"">" & _
"<property name=""label"">_Jelly (*.jfp)</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""receives_default"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">When active:" & CHR(10) & _
"generate Jelly-Projekt-file '*.jfp' in main folder, if not exists</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""xalign"">0</property>" & _
"<property name=""draw_indicator"">True</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">True</property>" & _
"<property name=""fill"">True</property>" & _
"<property name=""position"">5</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkCheckButton"" id=""CheWin"">" & _
"<property name=""label"">Reso_urce (*.rc)</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""receives_default"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">When active:" & CHR(10) & _
"generate Windows-Resource-Datei '*.rc' in main folder, if not exists</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""xalign"">0</property>" & _
"<property name=""draw_indicator"">True</property>" & _
"<signal name=""toggled"" handler=""on_CheWin_toggled"" swapped=""no""/>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">True</property>" & _
"<property name=""fill"">True</property>" & _
"<property name=""position"">6</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkCheckButton"" id=""CheRc"">" & _
"<property name=""label"">Icon in (*.r_c)</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""sensitive"">False</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""receives_default"">False</property>" & _
"<property name=""tooltip_text"" translatable=""yes"">When active:" & CHR(10) & _
"bind Icon file '*.ico' in Windows Resource file (*.rc)</property>" & _
"<property name=""use_action_appearance"">False</property>" & _
"<property name=""use_underline"">True</property>" & _
"<property name=""xalign"">0</property>" & _
"<property name=""image_position"">right</property>" & _
"<property name=""draw_indicator"">True</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">True</property>" & _
"<property name=""fill"">True</property>" & _
"<property name=""position"">7</property>" & _
"</packing>" & _
"</child>" & _
"</object>" & _
"</child>" & _
"<child type=""label"">" & _
"<object class=""GtkLabel"" id=""GtkLabel8"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""xpad"">5</property>" & _
"<property name=""label"" translatable=""yes"">&lt;b&gt;Project files&lt;/b&gt;</property>" & _
"<property name=""use_markup"">True</property>" & _
"</object>" & _
"</child>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">False</property>" & _
"<property name=""fill"">False</property>" & _
"<property name=""position"">1</property>" & _
"</packing>" & _
"</child>" & _
"</object>" & _
"</child>" & _
"<child type=""tab"">" & _
"<object class=""GtkLabel"" id=""GtkLabel9"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">True</property>" & _
"<property name=""can_default"">True</property>" & _
"<property name=""xpad"">4</property>" & _
"<property name=""ypad"">2</property>" & _
"<property name=""label"" translatable=""yes"">_Parameters</property>" & _
"<property name=""use_underline"">True</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""tab_fill"">False</property>" & _
"</packing>" & _
"</child>" & _
"<child>" & _
"<object class=""GtkScrolledWindow"" id=""scrolledwindow1"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">True</property>" & _
"<property name=""border_width"">5</property>" & _
"<property name=""window_placement_set"">True</property>" & _
"<property name=""shadow_type"">in</property>" & _
"<child>" & _
"<object class=""GtkTextView"" id=""TeVMessage"">" & _
"<property name=""width_request"">540</property>" & _
"<property name=""height_request"">260</property>" & _
"<property name=""visible"">True</property>" & _
"<property name=""app_paintable"">True</property>" & _
"<property name=""can_focus"">True</property>" & _
"<property name=""editable"">False</property>" & _
"<property name=""left_margin"">2</property>" & _
"<property name=""right_margin"">2</property>" & _
"<property name=""accepts_tab"">False</property>" & _
"</object>" & _
"</child>" & _
"</object>" & _
"<packing>" & _
"<property name=""position"">1</property>" & _
"</packing>" & _
"</child>" & _
"<child type=""tab"">" & _
"<object class=""GtkLabel"" id=""GtkLabel10"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">True</property>" & _
"<property name=""can_default"">True</property>" & _
"<property name=""xpad"">4</property>" & _
"<property name=""ypad"">2</property>" & _
"<property name=""label"" translatable=""yes"">_Outputs</property>" & _
"<property name=""use_underline"">True</property>" & _
"</object>" & _
"<packing>" & _
"<property name=""position"">1</property>" & _
"<property name=""tab_fill"">False</property>" & _
"</packing>" & _
"</child>" & _
"</object>" & _
"<packing>" & _
"<property name=""expand"">True</property>" & _
"<property name=""fill"">True</property>" & _
"<property name=""padding"">5</property>" & _
"<property name=""position"">2</property>" & _
"</packing>" & _
"</child>" & _
"</object>" & _
"</child>" & _
"</object>" & _
"<object class=""GtkAccelGroup"" id=""accelgroup1""/>" & _
"<object class=""GtkImage"" id=""image1"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""stock"">gtk-save</property>" & _
"<property name=""icon-size"">1</property>" & _
"</object>" & _
"<object class=""GtkImage"" id=""image2"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""stock"">gtk-open</property>" & _
"<property name=""icon-size"">1</property>" & _
"</object>" & _
"<object class=""GtkImage"" id=""image3"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""stock"">gtk-remove</property>" & _
"<property name=""icon-size"">1</property>" & _
"</object>" & _
"<object class=""GtkImage"" id=""image4"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""stock"">gtk-edit</property>" & _
"<property name=""icon-size"">1</property>" & _
"</object>" & _
"<object class=""GtkImage"" id=""image5"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""stock"">gtk-quit</property>" & _
"<property name=""icon-size"">1</property>" & _
"</object>" & _
"<object class=""GtkImage"" id=""image6"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""stock"">gtk-preferences</property>" & _
"<property name=""icon-size"">1</property>" & _
"</object>" & _
"<object class=""GtkImage"" id=""image7"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""stock"">gtk-index</property>" & _
"<property name=""icon-size"">1</property>" & _
"</object>" & _
"<object class=""GtkImage"" id=""image8"">" & _
"<property name=""visible"">True</property>" & _
"<property name=""can_focus"">False</property>" & _
"<property name=""stock"">gtk-save</property>" & _
"<property name=""icon-size"">1</property>" & _
"</object>" & _
"</interface>"
