' ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
'< callback modul generated by utility                         GladeToBac V3.0 >
'< callback-Modul erzeugt von                                                  >
'< Generated at / Generierung am                             2011-05-14, 13:44 >
' -----------------------------------------------------------------------------
'< Main/Haupt Program name: GladeToBac.bas                                     >
'<  Email:  Thomas[ dot ]Freiherr{ at }gmx{ dot }net                           >
'<    WWW:  www.freebasic-portal.de                                            >
' -----------------------------------------------------------------------------
'< callback SUB/FUNCTION                                          insert code! >
'< Ereignis Unterprogramm/Funktion                        Quelltext einfuegen! >
' vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

SUB on_MnuHelp_activate CDECL ALIAS "on_MnuHelp_activate" ( _
  BYVAL menuitem AS GtkMenuItem PTR, _
  BYVAL user_data AS gpointer) EXPORT

WITH _UI_
  .RausClr(*__("Help function") & NL & NL)
  .Folder(EXEPATH)
  VAR n = PROJ_NAME & "_" & *__("ReadMe") & ".txt", fnr = FREEFILE
  IF 0 = .No(OPEN(n FOR INPUT AS #fnr), n) THEN
    .Raus(":" & NL & NL)
    VAR t = "", z = ""
    WHILE NOT EOF(fnr)
      LINE INPUT #fnr, z
      t &= z & NL
    WEND : CLOSE #fnr
    .Raus(t, 1)
  END IF

  .RausBlau(*__("Command-line-help") & NL & NL)
  .Raus(HELP_TEXT, 1)

END WITH

END SUB
