' ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
'< callback modul generated by utility                         GladeToBac V3.0 >
'< callback-Modul erzeugt von                                                  >
'< Generated at / Generierung am                             2011-05-14, 13:44 >
' -----------------------------------------------------------------------------
'< Main/Haupt Program name: GladeToBac.bas                                     >
'<  Email:  Thomas[ dot ]Freiherr{ at }gmx{ dot }net                           >
'<    WWW:  www.freebasic-portal.de                                            >
' -----------------------------------------------------------------------------
'< callback SUB/FUNCTION                                          insert code! >
'< Ereignis Unterprogramm/Funktion                        Quelltext einfuegen! >
' vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

FUNCTION on_win_main_configure_event CDECL ALIAS "on_win_main_configure_event" ( _
  BYVAL widget AS GtkWidget PTR, _
  BYVAL event AS GdkEventConfigure PTR, _
  BYVAL user_data AS gpointer) AS gboolean EXPORT

WITH _UI_
  gtk_window_get_size(GTK_WINDOW(GUI.WinMain), @.Brei, @.Hoch)
END WITH : RETURN FALSE

END FUNCTION
